version: "3.8"
services:
    frontend:
        container_name: front
        build: frontend/
        image: zarritas/frontend:latest
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/app
        working_dir: /app
        networks:
            prueba:
              ipv4_address: 172.19.0.4
        hostname: front
    backend:
        container_name: back
        build: backend/
        image: zarritas/tomcat:latest
        volumes:
          - ./backend/build/libs:/usr/local/tomcat/webapps
        networks:
          prueba:
            ipv4_address: 172.19.0.2
        hostname: back
    mysql:
        container_name: database
        build: mysql/
        image: zarritas/mysql:latest
        ports:
            - "3306:3306"
        networks:
          prueba:
            ipv4_address: 172.19.0.3
        hostname: database
networks:
  prueba:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16